FROM node:12.2.0

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get -qq update && \ 
    apt-get -qq install -y apt-utils && \
    apt-get dist-upgrade -y 

RUN apt-get -qq install -y zip \
    # cypress.io deps
    libgtk2.0-0 libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 xvfb \
    # aws deps
    python-dev python-pip less vim ocaml libelf-dev && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


RUN pip install awscli --upgrade --quiet

# rsync here somehere
COPY . /

RUN npm i && npm completion >> ~/.bashrc 
#&& npm run build

EXPOSE 3000 8080 9229

CMD [ "node", "-r", "esm", "./app/server.js" ]
